multipass: true
full: true

plugins:
  - cleanupAttrs
  - cleanupEnableBackground
  - cleanupIDs
  - cleanupListOfValues
  - cleanupNumericValues
  - collapseGroups
  - convertColors
  - convertPathData
  - convertShapeToPath
  - convertStyleToAttrs
  - convertTransform
  - inlineStyles
  - mergePaths
  - minifyStyles
  - moveElemsAttrsToGroup
  - moveGroupAttrsToElems
  - prefixIds
  - removeAttrs
  - removeComments
  - removeDesc
  - removeDimensions
  - removeDoctype
  - removeEditorsNSData
  - removeElementsByAttr
  - removeEmptyAttrs
  - removeEmptyContainers
  - removeEmptyText
  - removeHiddenElems
  - removeMetadata
  - removeNonInheritableGroupAttrs
  - removeRasterImages
  - removeScriptElement
  - removeStyleElement
  - removeTitle
  - removeUnknownsAndDefaults
  - removeUnusedNS
  - removeUselessDefs
  - removeUselessStrokeAndFill
  - removeViewBox
  - removeXMLNS
  - removeXMLProcInst
  - sortAttrs
