tap "gromgit/fuse"
tap "homebrew/autoupdate"
tap "macos-fuse-t/cask"
tap "mongodb/brew"
tap "stek29/idevice"
brew "apktool"
brew "aria2"
brew "autoconf"
brew "automake"
brew "autossh"
brew "awscli"
brew "bat"
brew "btop"
brew "cabextract"
brew "caddy"
brew "cdrtools"
brew "cloc"
brew "closure-compiler"
brew "cloudflared"
brew "cmake"
brew "cmark"
brew "cmus"
brew "colima"
brew "composer"
brew "curl"
brew "ddrescue"
brew "deno"
brew "diskonaut"
brew "docker-compose"
brew "docker"
brew "dos2unix"
brew "dpkg"
brew "eza"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gawk"
brew "gh"
brew "ghostscript"
brew "gifsicle"
brew "git"
brew "gnu-getopt", link: true
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-which"
brew "gnupg"
brew "go-task"
brew "go"
brew "grep"
brew "gromgit/fuse/ntfs-3g-mac"
brew "gzip"
brew "htop"
brew "hub"
brew "ideviceinstaller"
brew "iftop"
brew "imagemagick"
brew "ipatool"
brew "iperf"
brew "iperf3"
brew "ipsw"
brew "irssi"
brew "jq"
brew "kubernetes-cli"
brew "lame"
brew "ldid-procursus"
brew "less"
brew "libimobiledevice"
brew "libirecovery"
brew "libtool"
brew "lima"
brew "m1ddc"
brew "make"
brew "mariadb", restart_service: :changed
brew "mas"
brew "media-info"
brew "megatools"
brew "minicom"
brew "miniupnpc"
brew "mole"
brew "mongodb/brew/mongodb-community-shell"
brew "mongodb/brew/mongodb-community"
brew "nano"
brew "ninja"
brew "nmap"
brew "node"
brew "oxipng"
brew "p7zip"
brew "parallel"
brew "perl"
brew "php"
brew "pinentry-mac"
brew "pinentry"
brew "pipx"
brew "pv"
brew "pyenv"
brew "python@3.14"
brew "python@3.9"
brew "q"
brew "qemu"
brew "rdap"
brew "redis", restart_service: :changed
brew "ripgrep"
brew "rsync"
brew "rtmpdump"
brew "ruby", link: true
brew "rust"
brew "rustup"
brew "s3cmd"
brew "scrcpy"
brew "sentry-cli"
brew "sleepwatcher", restart_service: :changed
brew "smartmontools"
brew "socat"
brew "stek29/idevice/img4tool"
brew "swiftlint"
brew "tailscale"
brew "telnet"
brew "tesseract"
brew "tmux"
brew "unshield"
brew "uutils-coreutils"
brew "uutils-diffutils"
brew "uutils-findutils"
brew "vbindiff"
brew "vttest"
brew "wget"
brew "wget2"
brew "wimlib"
brew "xz"
brew "yt-dlp"
brew "zip", link: true
brew "zopfli"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "zsh"
brew "zstd"
cask "1password-cli"
cask "1password"
cask "affinity"
cask "aldente"
cask "android-platform-tools"
cask "archaeology"
cask "asset-catalog-tinkerer"
cask "audacity"
cask "audio-hijack"
cask "backblaze"
cask "bettermouse"
cask "blackhole-2ch"
cask "bonjeff"
cask "charles"
cask "chatty"
cask "checkra1n"
cask "coconutbattery"
cask "cyberduck"
cask "daisydisk"
cask "dash"
cask "datagrip"
cask "db-browser-for-sqlite"
cask "dbeaver-community"
cask "deskpad"
cask "discord@ptb"
cask "disk-inventory-x"
cask "dosbox-x-app"
cask "dotnet-sdk"
cask "ente"
cask "figma"
cask "firefox@developer-edition"
cask "fission"
cask "font-inter"
cask "font-jetbrains-mono"
cask "fuse-t"
cask "ghostty"
cask "gimp"
cask "google-chrome"
cask "gpg-suite"
cask "handbrake-app"
cask "hopper-disassembler"
cask "iina"
cask "ilspy"
cask "imageoptim"
cask "imhex"
cask "insomnia"
cask "iterm2@beta"
cask "jtool2"
cask "karabiner-elements"
cask "localsend"
cask "mac-monitor"
cask "maccy"
cask "macfuse@dev"
cask "macs-fan-control"
cask "macsymbolicator"
cask "mediainfo"
cask "minecraft"
cask "mongodb-compass"
cask "monitorcontrol"
cask "mounty"
cask "netnewswire"
cask "ngrok"
cask "obs"
cask "obsidian"
cask "orbstack"
cask "orcaslicer"
cask "parsec"
cask "raycast"
cask "rider"
cask "roblox"
cask "rustdesk"
cask "safari-technology-preview"
cask "secretive"
cask "sf-symbols"
cask "sketch"
cask "soulver"
cask "soundsource"
cask "studio-3t"
cask "sublime-merge"
cask "sublime-text"
cask "suspicious-package"
cask "tailscale-app"
cask "temurin"
cask "textual"
cask "the-unarchiver"
cask "thunderbird@beta"
cask "transmission"
cask "ungoogled-chromium"
cask "utm"
cask "visual-studio-code"
cask "vivid-app"
cask "vlc"
cask "vnc-viewer"
cask "wakatime"
cask "webstorm"
cask "whatsyoursign"
cask "windows-app"
cask "wireshark-app"
cask "xcodes-app"
cask "zoom"
mas "Apple Configurator", id: 1037126344
mas "Brother iPrint&Scan", id: 1193539993
mas "Day Progress", id: 6450280202
mas "DevTools", id: 6444775708
mas "Final Cut Pro", id: 424389933
mas "Flighty", id: 1358823008
mas "Folder Quick Look", id: 6753110395
mas "Ivory", id: 6444602274
mas "Keyshape", id: 1223341056
mas "Logic Pro", id: 634148309
mas "Mactracker", id: 430255202
mas "Manet", id: 6470928235
mas "Medis", id: 1579200037
mas "Meta", id: 558317092
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Word", id: 462054704
mas "Pixelmator Pro", id: 1289583905
mas "Plash", id: 1494023538
mas "Sequel Ace", id: 1518036000
mas "Tailscale", id: 1475387142
mas "Telephone", id: 406825478
mas "TestFlight", id: 899247664
mas "Things", id: 904280696
mas "Timery", id: 1425368544
mas "Wayback Machine", id: 1472432422
mas "Whisper Transcription", id: 1668083311
