#!/bin/bash
# Config
cd ~
shopt -s dotglob

# Functions
status() {
	printf "\e[0;32m==> \e[1;39m%s…\e[m\n" "$1" >&2
}

unsafe_run() {
	printf "\e[0;36m==> \e[1;39m%s\e[m\n" "$*" >&2
	"$@"
}

run() {
	unsafe_run "$@"
	result=$?

	if [[ $result != 0 ]]; then
		printf "\e[0;31m==> \e[1;31mError:\e[m %s\n" "Return code $result"
		exit $result
	fi
}

wait_for_process() {
	status "Waiting for $1"

	while pgrep "$1" >/dev/null 2>/dev/null; do
		sleep 5
	done
}

has() {
	hash "$1" 2>/dev/null
}

open_if_exists() {
	[[ -d "$1" ]] && run open "$1"
}

# -1: Sanity check the distro
[[ -f /etc/lsb-release ]] && source /etc/lsb-release

if [[ $DISTRIB_ID != Ubuntu ]]; then
	echo "This script is only tested on Ubuntu. Aborting." >&2
	exit 1
fi

[[ $UID != 0 ]] && SUDO=sudo

# 0: Initial setup
status "Configuring APT"
run $SUDO sed -Ei sX'^# (deb http://archive\.ubuntu\.com)'X'\1'Xg /etc/apt/sources.list
run $SUDO sed -i sX'archive\.ubuntu\.com'X'mirror.internode.on.net/pub/ubuntu'Xg /etc/apt/sources.list

# 1: Add repos
status "Adding repos"
DEB_HOST_ARCH=$(dpkg-architecture -qDEB_HOST_ARCH)

# apt-fast
if ! has apt-fast; then
	run curl -fsSL 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x1ee2ff37ca8da16b' | gpg --dearmor | $SUDO tee /usr/share/keyrings/apt-fast.gpg >/dev/null
	run printf 'deb [signed-by=%s] %s %s main\n' /usr/share/keyrings/apt-fast.gpg http://ppa.launchpad.net/apt-fast/stable/ubuntu/ $DISTRIB_CODENAME | $SUDO tee /etc/apt/sources.list.d/apt-fast.list
fi

# node.js
if ! has node; then
	run curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | $SUDO tee /usr/share/keyrings/nodesource.gpg >/dev/null
	run printf 'deb [arch=%s signed-by=%s] %s %s main\n' $DEB_HOST_ARCH /usr/share/keyrings/nodesource.gpg https://deb.nodesource.com/node_16.x $DISTRIB_CODENAME | $SUDO tee /etc/apt/sources.list.d/nodesource.list
fi

# Docker
if ! has docker; then
	run curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor | $SUDO tee /usr/share/keyrings/docker-archive-keyring.gpg >/dev/null
	run printf 'deb [arch=%s signed-by=%s] %s %s stable\n' $DEB_HOST_ARCH /usr/share/keyrings/docker-archive-keyring.gpg https://download.docker.com/linux/ubuntu $DISTRIB_CODENAME | $SUDO tee /etc/apt/sources.list.d/docker.list
fi

# 2: Install stuff
status "Installing packages"
export DEBIAN_FRONTEND=noninteractive
run $SUDO apt-get update
run $SUDO apt-get install -yq apt-fast
run $SUDO apt-fast dist-upgrade -yq
run $SUDO apt-fast install -yq \
	build-essential dpkg-dev git fontconfig \
	zsh zsh-autosuggestions zsh-syntax-highlighting \
	htop iotop iftop powertop tmux \
	bat fzf \
	nano imagemagick jq p7zip-full zip unzip zstd openssh-client rsync curl wget aria2 optipng \
	android-sdk-platform-tools \
	libimobiledevice-utils usbmuxd libplist-utils \
	fonts-roboto fonts-noto-color-emoji ttf-mscorefonts-installer \
	nodejs \
	docker-ce docker-ce-cli containerd.io
# Extra packages only available later than focal
[[ ${DISTRIB_RELEASE%.*} -ge 21 ]] && run $SUDO apt-fast install -yq \
	exa fonts-jetbrains-mono
run $SUDO apt-fast autoremove -yq
run $SUDO apt-fast clean -q

# 3: Install pnpm
status "Installing pnpm"
if ! has pnpm; then
	curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm
fi

# 4: Configure user groups
status "Adding user to docker group"
if [[ $UID != 0 ]]; then
	run $SUDO usermod -aG docker $USER
fi

# 5: Set login shell
status "Setting shell to zsh"
run $SUDO chsh -s $(which zsh) $USER

# 6: Done
status "Done! Reboot now"
