#!/usr/bin/env zsh

# Defaults
alias ls='ls -blaphtF --color'
alias less='less -x2'
alias grep='grep --color -in --exclude-dir={.bzr,.cvs,.git,.hg,.svn,.theos} --exclude=\*.map'
alias wget='wget --content-disposition'
alias ssh='nocorrect ssh'
alias strings='strings -a'
alias youtube-dl='youtube-dl --merge-output-format mp4 --audio-format m4a'
alias pv='pv -W'
alias ip='ip --color'
alias ipb='ip --color --brief'
alias du='du --apparent-size'
# alias rsync='rsync -EX' # TODO: bad idea? not sure…
alias tmux='tmux -2f ~/.dotfiles/.tmux.conf $TMUX_CC_FLAG'
alias fzf=fzf-tmux

if [[ $VENDOR == apple ]]; then
	alias ping='ping --apple-time'
fi

if has bat; then
	alias less=bat
fi

if has exa; then
	alias ls='exa -blah -tmodified'
fi

# Kinda-sorta functions
alias filesize='stat -c %s'
alias finder='open -R'
alias logcat='logcat-color --stay-connected -v threadtime'

# Shorter names
alias vboxmanage=VBoxManage
alias vbox=VBoxManage
alias plistbuddy=/usr/libexec/PlistBuddy
alias plbuddy=/usr/libexec/PlistBuddy
alias xcselect=xcode-select
alias xcsel=xcode-select
alias hop='hopperv4 -e'
alias f=fzf
alias n=pnpm
alias y=pnpm
alias t=task
alias m=make

# Cross-platform normalisation
alias pbcopy=clipcopy
alias pbpaste=clippaste

# If we have hub, alias git completion to it
if has hub; then
	compdef hub=git
fi

# Theos
alias nic='$THEOS/bin/nic.pl'
alias logify='$THEOS/bin/logify.pl'
alias logos='$THEOS/bin/logos.pl'
alias nicify='$THEOS/bin/nicify.pl'
alias denicify='$THEOS/bin/denicify.pl'

# Apps
if [[ $VENDOR == apple ]]; then
	alias iterm='open -b com.googlecode.iterm2'
	alias it=iterm
	alias it2=iterm
	alias pxm='open -b com.pixelmatorteam.pixelmator.x'
	alias psd='open -b com.adobe.Photoshop'
	alias vlc='open -b org.videolan.vlc'
	alias io='open -b net.pornel.ImageOptim'
fi

# Apple Silicon
if [[ $VENDOR == apple && $MACHTYPE == aarch64 && $CPUTYPE == arm64 ]]; then
	alias x86='arch -x86_64'
	alias sudox86='sudo arch -x86_64'
	alias xy='arch -x86_64 yarn'
fi

# Typos
alias kilall=killall
alias kilalll=killall
alias killlal=killall
alias killal=killall
alias killalll=killall
alias killalal=killall
alias sl=ls
alias ks=ls
alias lks=ls
alias kls=ls
alias l=ls
alias s=ls
alias dc=cd
alias c=cd
alias d=cd
alias anno=nano
alias lss=less
alias les=less
alias got=git
alias gti=git
alias gi=git
alias gt=git
alias g=git
alias it=git
alias gut=git
alias giut=git
alias gikt=git
alias nom=npm
alias n0m=npm
alias grpe=grep
alias grp=grep
alias gep=grep
