#!/usr/bin/env zsh

# handle command not found by displaying packages that contain the command
command_not_found_handler() {
	# lazy load the proper handler on the first run
	if has brew && brew command command-not-found-init >/dev/null; then
		eval "$(brew command-not-found-init)"
		command_not_found_handler $*
	elif [[ -x /etc/zsh_command_not_found ]]; then
		source /etc/zsh_command_not_found
		command_not_found_handler $*
	else
		return 127
	fi
}

# convenience to set THEOS_DEVICE_IP. used to do a lot more than this, but theos
# has now removed all need for anything special, and it's stuck in muscle memory
setdevice() {
	export THEOS_DEVICE_IP=$1
	echo "$THEOS_DEVICE_IP"
}

# convenience to switch xcode versions
xcswitch() {
	sudo xcode-select -switch "/Applications/Xcode$1.app/Contents/Developer" && \
		echo "Switched to $(xcsel -print-path)"
}

# highlighted man pages!!
# http://boredzo.org/blog/archives/2016-08-15/colorized-man-pages-understood-and-customized
unalias man

man() {
	env \
		LESS_TERMCAP_mb=$'\e[1;31m' LESS_TERMCAP_md=$'\e[1;31m' \
		LESS_TERMCAP_me=$'\e[0m' LESS_TERMCAP_se=$'\e[0m' \
		LESS_TERMCAP_so=$'\e[1;44;33m' LESS_TERMCAP_ue=$'\e[0m' \
		LESS_TERMCAP_us=$'\e[1;32m' \
		man "$@"
}
