#!/usr/bin/env zsh

# defaults
alias ls='ls -blaphtF --color'
alias less='less -x2'
alias grep='grep --color -in --exclude-dir={.bzr,.cvs,.git,.hg,.svn,.theos}'
alias wget='wget --content-disposition'
alias ssh='nocorrect ssh'
alias strings='strings -a'
alias youtube-dl='youtube-dl --merge-output-format mp4 --audio-format m4a'
alias pv='pv -W'
alias ip='ip --color'
alias ipb='ip --color --brief'

if [[ $VENDOR == apple ]]; then
	alias ping='ping --apple-time'
fi

# kinda-sorta functions
alias filesize='stat -c %s'
alias finder='open -R'
alias reload='. ~/.zshrc'

# shorter names
alias vboxmanage=VBoxManage
alias vbox=VBoxManage
alias plistbuddy=/usr/libexec/PlistBuddy
alias plbuddy=/usr/libexec/PlistBuddy
alias xcselect=xcode-select
alias xcsel=xcode-select
alias hop='hopperv4 -e'
alias io=optim
alias n=npm
alias y=yarn

# cross-platform normalisation
if has afplay; then
	alias play=afplay
elif has aplay; then
	alias play=aplay
fi

alias pbcopy=clipcopy
alias pbpaste=clippaste

# if we have hub, alias git completion to it
if has hub; then
	compdef hub=git
fi

# theos
alias nic='$THEOS/bin/nic.pl'
alias logify='$THEOS/bin/logify.pl'
alias logos='$THEOS/bin/logos.pl'
alias nicify='$THEOS/bin/nicify.pl'
alias denicify='$THEOS/bin/denicify.pl'

# apps
alias tview='open /Applications/TeamViewer.app'
alias pxm='open -b com.pixelmatorteam.pixelmator'
alias psd='open -b com.adobe.Photoshop'
alias xcode='open -b com.apple.dt.xcode'
alias cr='open -b com.google.Chrome'
alias vlc='open -b org.videolan.vlc'
alias optim='open -b net.pornel.ImageOptim'
alias alpha='open -b net.pornel.ImageAlpha'
alias subl=atom

# typos
alias kilall=killall
alias kilalll=killall
alias killlal=killall
alias killal=killall
alias killalll=killall
alias killalal=killall
alias sl=ls
alias ks=ls
alias lks=ls
alias kls=ls
alias l=ls
alias s=ls
alias dc=cd
alias c=cd
alias d=cd
alias anno=nano
alias lss=less
alias les=less
alias got=git
alias gti=git
alias gi=git
alias gt=git
alias g=git
alias it=git
alias gut=git
alias giut=git
alias gikt=git
alias nom=npm
alias n0m=npm
alias grpe=grep
alias grp=grep
alias gep=grep
